### ISSUE TITLE
docker compose

### ISSUE THREAD

**Issue by markrennie71** [madmachinations/home-assistant-alexa-shopping-list#19]
Hello

Do you have an example of a docker compose file or docker CLI please?

Cheers

**Comment by madmachinations** [comment]
I do not I'm afraid, all mine are running on Kubernetes.

Here's something off-the-cuff to get you started:

```
version: '3'

services:
  alexa-shopping-list-sync:
    image: madmachinations/ha-alexa-shopping-list-sync:latest
    ports:
      - "4000:4000" 
```
